CREATE TABLE trees (
	TREE_ID SERIAL PRIMARY KEY NOT NULL,
	Familyname VARCHAR(30) NOT NULL,
	NumMembers INT NOT NULL
);
CREATE TABLE ancestors (
	ANCESTOR_ID SERIAL PRIMARY KEY NOT NULL,
	TREE_ID SERIAL REFERENCES trees(TREE_ID),
	USER_ID SERIAL REFERENCES users(user_id),
	Firstname VARCHAR(99) NOT NULL,
	Lastname VARCHAR(99) NOT NULL
);
CREATE TABLE ancestor_info (
	INFO_ID SERIAL PRIMARY KEY NOT NULL,
	Filepath TEXT NOT NULL,
	Filename VARCHAR(99) NOT NULL UNIQUE,
	ANCESTOR_ID SERIAL REFERENCES ancestors(ANCESTOR_ID)
)